name: Frontend
run-name: Frontend (${{ github.actor }})
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd frontend-react && npm ci
      - name: Lint frontend code
        run: |
          cd frontend-react && npm run lint
  pretty:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install packages
        run: |
          cd frontend-react && npm ci
      - name: Prettier check frontend code
        run: |
          cd frontend-react && npm run prettier
      - run: echo "ğŸ This job's status is ${{ job.status }}."
